openapi: 3.0.0
info:
  title: Jobs API
  contact: {}
  version: '1.0'
servers:
  - url: https://jobs-api-7hgg.onrender.com/api/v1
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/RegisterRequest'
                - example:
                    name: Megagig
                    email: megagig@gmail.com
                    password: '123456'
            example:
              name: Megagig
              email: megagig@gmail.com
              password: '123456'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/LoginRequest'
                - example:
                    email: megagig@gmail.com
                    password: '123456'
            example:
              email: megagig@gmail.com
              password: '123456'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create  A Job
      operationId: CreateAJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CreateAJobRequest'
                - example:
                    company: Obitex Electronics
                    description: Electronics
                    position: CEO
                    location: OTA
                    salary: 10000
                    jobType: Sales
                    experience: 2 years experience
                    skills: Management
            example:
              company: Obitex Electronics
              description: Electronics
              position: CEO
              location: OTA
              salary: 10000
              jobType: Sales
              experience: 2 years experience
              skills: Management
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/673ddbeba9291103e2787aea:
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/673dd1dea9291103e2787ae3:
    get:
      tags:
        - Jobs
      summary: Get A Single Job
      operationId: GetASingleJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Jobs
      summary: Update A Single Job
      operationId: UpdateASingleJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/UpdateASingleJobRequest'
                - example:
                    company: Megagig
                    position: CEO
            example:
              company: Megagig
              position: CEO
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
components:
  schemas:
    RegisterRequest:
      title: RegisterRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Megagig
        email: megagig@gmail.com
        password: '123456'
    LoginRequest:
      title: LoginRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: megagig@gmail.com
        password: '123456'
    CreateAJobRequest:
      title: CreateAJobRequest
      required:
        - company
        - description
        - position
        - location
        - salary
        - jobType
        - experience
        - skills
      type: object
      properties:
        company:
          type: string
        description:
          type: string
        position:
          type: string
        location:
          type: string
        salary:
          type: integer
          format: int32
        jobType:
          type: string
        experience:
          type: string
        skills:
          type: string
      example:
        company: Obitex Electronics
        description: Electronics
        position: CEO
        location: OTA
        salary: 10000
        jobType: Sales
        experience: 2 years experience
        skills: Management
    UpdateASingleJobRequest:
      title: UpdateASingleJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Megagig
        position: CEO
    DeleteJobRequest:
      title: DeleteJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Megagig
        position: CEO
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Authentication
  - name: Jobs
